name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: xcc-utilities-snap
          path: "*.snap"